name: tests unitaires

on: [push]

jobs:
  test1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pytest
        run: pip install pytest

      - name: Voir les fichiers
        run: find . -maxdepth 3 -type f

      - name: Afficher la branche
        run: echo "Nom branche: ${{ github.ref }}"

      - name: Afficher l'OS
        run: echo "OS de la VM: ${{ runner.os }}"

      - name: Run tests
        run: pytest TP1/test.py
