name: tests unitaires

on:
  push:

jobs:
  test1:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Installer pytest
        run: pip install pytest

      - name: Voir les fichiers
        run: find . -maxdepth 3 -type f

      - name: Tester le terminal
        run: echo "Bonjour"

      - name: Lancer les tests
        run: pytest TP1/test.py

